version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "3000"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5
  
  users:
    build:
      context: .
      dockerfile: apps/users-service/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "3000"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  messages:
    build:
      context: .
      dockerfile: apps/messages-service/Dockerfile
    ports:
      - "4000:3000"
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "nc", "-z", "localhost", "3000"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: apps/youapp-api-gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - auth
        # condition: service_healthy
      - users
        # condition: service_healthy
      - messages
        # condition: service_healthy
